create_clock -period 8.000 -name VIRTUAL_clk_out1_clk_wiz_0 -waveform {0.000 4.000}





## Input Delay Constraint
set_input_delay -clock VIRTUAL_clk_out1_clk_wiz_0 -max 0.000 [get_ports {reset read_slice {serial_in_img[*]}}]
set_input_delay -clock VIRTUAL_clk_out1_clk_wiz_0 -min 0.000 [get_ports {reset read_slice {serial_in_img[*]}}]

# Output Delay Constraint
set_output_delay -clock VIRTUAL_clk_out1_clk_wiz_0 -max 0.000 [get_ports {load_res ready {serial_out_conv[*]}}]
set_output_delay -clock VIRTUAL_clk_out1_clk_wiz_0 -min 0.000 [get_ports {load_res ready {serial_out_conv[*]}}]

# derive_pll_clocks -create_base_clocks
# derive_clock_uncertainty

set_property CFGBVS GND [current_design]
set_property CONFIG_VOLTAGE 1.8 [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {serial_in_img[31]}]
set_property IOSTANDARD LVCMOS18 [get_ports {serial_in_img[30]}]
set_property IOSTANDARD LVCMOS18 [get_ports {serial_in_img[29]}]
set_property IOSTANDARD LVCMOS18 [get_ports {serial_in_img[28]}]
set_property IOSTANDARD LVCMOS18 [get_ports {serial_in_img[27]}]
set_property IOSTANDARD LVCMOS18 [get_ports {serial_in_img[26]}]
set_property IOSTANDARD LVCMOS18 [get_ports {serial_in_img[25]}]
set_property IOSTANDARD LVCMOS18 [get_ports {serial_in_img[24]}]
set_property IOSTANDARD LVCMOS18 [get_ports {serial_in_img[23]}]
set_property IOSTANDARD LVCMOS18 [get_ports {serial_in_img[22]}]
set_property IOSTANDARD LVCMOS18 [get_ports {serial_in_img[21]}]
set_property IOSTANDARD LVCMOS18 [get_ports {serial_in_img[20]}]
set_property IOSTANDARD LVCMOS18 [get_ports {serial_in_img[19]}]
set_property IOSTANDARD LVCMOS18 [get_ports {serial_in_img[18]}]
set_property IOSTANDARD LVCMOS18 [get_ports {serial_in_img[17]}]
set_property IOSTANDARD LVCMOS18 [get_ports {serial_in_img[16]}]
set_property IOSTANDARD LVCMOS18 [get_ports {serial_in_img[15]}]
set_property IOSTANDARD LVCMOS18 [get_ports {serial_in_img[14]}]
set_property IOSTANDARD LVCMOS18 [get_ports {serial_in_img[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports {serial_in_img[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {serial_in_img[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {serial_in_img[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {serial_in_img[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {serial_in_img[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {serial_in_img[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {serial_in_img[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {serial_in_img[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {serial_in_img[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {serial_in_img[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {serial_in_img[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {serial_in_img[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {serial_in_img[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {serial_out_conv[31]}]
set_property IOSTANDARD LVCMOS18 [get_ports {serial_out_conv[30]}]
set_property IOSTANDARD LVCMOS18 [get_ports {serial_out_conv[29]}]
set_property IOSTANDARD LVCMOS18 [get_ports {serial_out_conv[28]}]
set_property IOSTANDARD LVCMOS18 [get_ports {serial_out_conv[27]}]
set_property IOSTANDARD LVCMOS18 [get_ports {serial_out_conv[26]}]
set_property IOSTANDARD LVCMOS18 [get_ports {serial_out_conv[25]}]
set_property IOSTANDARD LVCMOS18 [get_ports {serial_out_conv[24]}]
set_property IOSTANDARD LVCMOS18 [get_ports {serial_out_conv[23]}]
set_property IOSTANDARD LVCMOS18 [get_ports {serial_out_conv[22]}]
set_property IOSTANDARD LVCMOS18 [get_ports {serial_out_conv[21]}]
set_property IOSTANDARD LVCMOS18 [get_ports {serial_out_conv[20]}]
set_property IOSTANDARD LVCMOS18 [get_ports {serial_out_conv[19]}]
set_property IOSTANDARD LVCMOS18 [get_ports {serial_out_conv[18]}]
set_property IOSTANDARD LVCMOS18 [get_ports {serial_out_conv[17]}]
set_property IOSTANDARD LVCMOS18 [get_ports {serial_out_conv[16]}]
set_property IOSTANDARD LVCMOS18 [get_ports {serial_out_conv[15]}]
set_property IOSTANDARD LVCMOS18 [get_ports {serial_out_conv[14]}]
set_property IOSTANDARD LVCMOS18 [get_ports {serial_out_conv[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports {serial_out_conv[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {serial_out_conv[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {serial_out_conv[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {serial_out_conv[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {serial_out_conv[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {serial_out_conv[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {serial_out_conv[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {serial_out_conv[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {serial_out_conv[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {serial_out_conv[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {serial_out_conv[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {serial_out_conv[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {serial_out_conv[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports clock]
set_property IOSTANDARD LVCMOS18 [get_ports load_res]
set_property IOSTANDARD LVCMOS18 [get_ports read_slice]
set_property IOSTANDARD LVCMOS18 [get_ports ready]
set_property IOSTANDARD LVCMOS18 [get_ports reset]

set_property PACKAGE_PIN AR29 [get_ports {serial_in_img[31]}]
set_property PACKAGE_PIN AT29 [get_ports {serial_in_img[30]}]
set_property PACKAGE_PIN AV25 [get_ports {serial_in_img[29]}]
set_property PACKAGE_PIN AV26 [get_ports {serial_in_img[28]}]
set_property PACKAGE_PIN AW27 [get_ports {serial_in_img[27]}]
set_property PACKAGE_PIN AW28 [get_ports {serial_in_img[26]}]
set_property PACKAGE_PIN AV28 [get_ports {serial_in_img[25]}]
set_property PACKAGE_PIN AU26 [get_ports {serial_in_img[24]}]
set_property PACKAGE_PIN AU27 [get_ports {serial_in_img[23]}]
set_property PACKAGE_PIN AR27 [get_ports {serial_in_img[22]}]
set_property PACKAGE_PIN AT27 [get_ports {serial_in_img[21]}]
set_property PACKAGE_PIN AP27 [get_ports {serial_in_img[20]}]
set_property PACKAGE_PIN AR28 [get_ports {serial_in_img[19]}]
set_property PACKAGE_PIN AN28 [get_ports {serial_in_img[18]}]
set_property PACKAGE_PIN AP28 [get_ports {serial_in_img[17]}]
set_property PACKAGE_PIN AT25 [get_ports {serial_in_img[16]}]
set_property PACKAGE_PIN AT26 [get_ports {serial_in_img[15]}]
set_property PACKAGE_PIN AP25 [get_ports {serial_in_img[14]}]
set_property PACKAGE_PIN AR25 [get_ports {serial_in_img[13]}]
set_property PACKAGE_PIN AN25 [get_ports {serial_in_img[12]}]
set_property PACKAGE_PIN AN26 [get_ports {serial_in_img[11]}]
set_property PACKAGE_PIN AM28 [get_ports {serial_in_img[10]}]
set_property PACKAGE_PIN AM29 [get_ports {serial_in_img[9]}]
set_property PACKAGE_PIN AK27 [get_ports {serial_in_img[8]}]
set_property PACKAGE_PIN AL27 [get_ports {serial_in_img[7]}]
set_property PACKAGE_PIN AM26 [get_ports {serial_in_img[6]}]
set_property PACKAGE_PIN AM27 [get_ports {serial_in_img[5]}]
set_property PACKAGE_PIN AK24 [get_ports {serial_in_img[4]}]
set_property PACKAGE_PIN AK25 [get_ports {serial_in_img[3]}]
set_property PACKAGE_PIN AL25 [get_ports {serial_in_img[2]}]
set_property PACKAGE_PIN AL26 [get_ports {serial_in_img[1]}]
set_property PACKAGE_PIN AJ25 [get_ports {serial_in_img[0]}]
set_property PACKAGE_PIN AU33 [get_ports {serial_out_conv[31]}]
set_property PACKAGE_PIN AR34 [get_ports {serial_out_conv[30]}]
set_property PACKAGE_PIN AT35 [get_ports {serial_out_conv[29]}]
set_property PACKAGE_PIN AU32 [get_ports {serial_out_conv[28]}]
set_property PACKAGE_PIN AV33 [get_ports {serial_out_conv[27]}]
set_property PACKAGE_PIN AW32 [get_ports {serial_out_conv[26]}]
set_property PACKAGE_PIN AW33 [get_ports {serial_out_conv[25]}]
set_property PACKAGE_PIN AV34 [get_ports {serial_out_conv[24]}]
set_property PACKAGE_PIN AV35 [get_ports {serial_out_conv[23]}]
set_property PACKAGE_PIN AY32 [get_ports {serial_out_conv[22]}]
set_property PACKAGE_PIN AY33 [get_ports {serial_out_conv[21]}]
set_property PACKAGE_PIN BA31 [get_ports {serial_out_conv[20]}]
set_property PACKAGE_PIN BA32 [get_ports {serial_out_conv[19]}]
set_property PACKAGE_PIN AW30 [get_ports {serial_out_conv[18]}]
set_property PACKAGE_PIN AY30 [get_ports {serial_out_conv[17]}]
set_property PACKAGE_PIN BA30 [get_ports {serial_out_conv[16]}]
set_property PACKAGE_PIN BB31 [get_ports {serial_out_conv[15]}]
set_property PACKAGE_PIN AV30 [get_ports {serial_out_conv[14]}]
set_property PACKAGE_PIN AW31 [get_ports {serial_out_conv[13]}]
set_property PACKAGE_PIN AR30 [get_ports {serial_out_conv[12]}]
set_property PACKAGE_PIN AT30 [get_ports {serial_out_conv[11]}]
set_property PACKAGE_PIN AU31 [get_ports {serial_out_conv[10]}]
set_property PACKAGE_PIN AV31 [get_ports {serial_out_conv[9]}]
set_property PACKAGE_PIN AN30 [get_ports {serial_out_conv[8]}]
set_property PACKAGE_PIN AP30 [get_ports {serial_out_conv[7]}]
set_property PACKAGE_PIN AP32 [get_ports {serial_out_conv[6]}]
set_property PACKAGE_PIN AR32 [get_ports {serial_out_conv[5]}]
set_property PACKAGE_PIN AN31 [get_ports {serial_out_conv[4]}]
set_property PACKAGE_PIN AP31 [get_ports {serial_out_conv[3]}]
set_property PACKAGE_PIN AP33 [get_ports {serial_out_conv[2]}]
set_property PACKAGE_PIN AR33 [get_ports {serial_out_conv[1]}]
set_property PACKAGE_PIN AT31 [get_ports {serial_out_conv[0]}]
set_property PACKAGE_PIN AU28 [get_ports clock]
set_property PACKAGE_PIN AW26 [get_ports read_slice]
set_property PACKAGE_PIN AP26 [get_ports load_res]
set_property PACKAGE_PIN AJ26 [get_ports ready]
set_property PACKAGE_PIN AW25 [get_ports reset]
